services:
  qc.acc_ginger_carefree_cobra:
    command: sleep 6000000
    image: bitnami/git:2.34.1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_cinnabar_dramatic_tiger:
    command: sleep 6000000
    image: bitnami/git:2.34.1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_heather_courageous_kraken:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc/markdownlint
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_periwinkle_perceptive_catfish:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_saffron_dramatic_angelfish:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc/restructuredtext-lint
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.lic_wisteria_lively_dhole:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-licensee:9.17.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sec_seafoam_stubborn_dolphin:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sec/bandit
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_reef_brilliant_manatee:
    command: sleep 6000000
    image: hadolint/hadolint:2.8.0-alpine
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_violet_anxious_fox:
    command: sleep 6000000
    image: pipelinecomponents/flake8:0.19.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.uni_harlequin_peppy_spren:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-pytest:7.1.3-alpha
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.ver_flint_loving_swan:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Ver
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
